CREATE TABLE NTCC_TRANSACTION 
(
  TRANSACTION_ID VARCHAR2(128) NOT NULL 
  , GLOBAL_TRANSACTION_ID VARCHAR2(128)
  , BRANCH_QUALIFIER VARCHAR2(128) 
  , STATUS NUMBER(9, 0) NOT NULL 
  , TRANSACTION_TYPE NUMBER(9, 0) NOT NULL 
  , RETRIED_COUNT NUMBER(9, 0) NOT NULL 
  , CREATE_UTC_TIME DATE NOT NULL 
  , LAST_UPDATE_UTC_TIME DATE NOT NULL 
  , VERSION NUMBER(9, 0) NOT NULL 
  , CONTENT CLOB 
  , CONSTRAINT PK_NTCC_TRANSACTION PRIMARY KEY 
  (
     TRANSACTION_ID 
  )
);
